workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Install Gradle
        script: |
          # Download and install Gradle directly
          wget -q https://services.gradle.org/distributions/gradle-8.4-bin.zip
          unzip -q gradle-8.4-bin.zip
          export GRADLE_HOME=$PWD/gradle-8.4
          export PATH=$GRADLE_HOME/bin:$PATH
          echo "export PATH=$PWD/gradle-8.4/bin:\$PATH" >> ~/.bashrc
          gradle --version
      - name: Fix BuildConfig issue
        script: |
          # Enable BuildConfig feature in app/build.gradle.kts
          if grep -q "buildFeatures" app/build.gradle.kts; then
            # If buildFeatures block exists, add buildConfig = true
            sed -i '/buildFeatures {/a\        buildConfig = true' app/build.gradle.kts
          else
            # If no buildFeatures block, add it after android block starts
            sed -i '/android {/a\    buildFeatures {\n        buildConfig = true\n    }' app/build.gradle.kts
          fi
          
          # Show the modified file to verify
          echo "Modified build.gradle.kts:"
          grep -A 10 -B 5 "buildFeatures\|buildConfig" app/build.gradle.kts || echo "BuildConfig configuration added"
      - name: Create keystore
        script: |
          mkdir -p keystore
          keytool -genkey -v -keystore keystore/release.keystore \
            -alias expense_tracker_key -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=ExpenseTracker, OU=Development, O=ExpenseTracker, L=City, S=State, C=US" \
            -storepass codemagic_build -keypass codemagic_build
      - name: Configure signing
        script: |
          echo "RELEASE_STORE_FILE=keystore/release.keystore" >> gradle.properties
          echo "RELEASE_STORE_PASSWORD=codemagic_build" >> gradle.properties
          echo "RELEASE_KEY_ALIAS=expense_tracker_key" >> gradle.properties
          echo "RELEASE_KEY_PASSWORD=codemagic_build" >> gradle.properties
      - name: Build Android release
        script: |
          # Use gradle directly instead of gradlew
          export PATH=$PWD/gradle-8.4/bin:$PATH
          gradle assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true