workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Create keystore
        script: |
          mkdir -p keystore
          keytool -genkey -v -keystore keystore/release.keystore \
            -alias expense_tracker_key -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=ExpenseTracker, OU=Development, O=ExpenseTracker, L=City, S=State, C=US" \
            -storepass codemagic_build -keypass codemagic_build
      - name: Configure signing
        script: |
          echo "RELEASE_STORE_FILE=keystore/release.keystore" >> gradle.properties
          echo "RELEASE_STORE_PASSWORD=codemagic_build" >> gradle.properties
          echo "RELEASE_KEY_ALIAS=expense_tracker_key" >> gradle.properties
          echo "RELEASE_KEY_PASSWORD=codemagic_build" >> gradle.properties
      - name: Build Android release
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true